# Generated by Django 3.0.3 on 2020-02-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_name', models.CharField(max_length=10)),
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('student_email', models.EmailField(max_length=50)),
                ('student_branch', models.CharField(max_length=20)),
                ('student_contact', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Student Information',
                'verbose_name_plural': 'Student Informations',
            },
        ),
    ]
