# Generated by Django 3.0.3 on 2020-02-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200217_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='contact',
            new_name='student_branch',
        ),
        migrations.AddField(
            model_name='student',
            name='student_contact',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
