# Generated by Django 3.0.3 on 2020-02-17 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200217_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student Information', 'verbose_name_plural': 'Student Informations'},
        ),
    ]
